module.exports = {
  env: {
    webextensions: true,
    browser: true,
    jest: true,
  },
  // ignorePatterns: ['.eslintrc.js'],
  globals: {
    React: true,
  },
  plugins: [`@typescript-eslint`, `unicorn`, `prettier`, `react-hooks`],
  extends: [
    `eslint:recommended`,
    `plugin:@typescript-eslint/recommended`,
    `airbnb`,
    `plugin:unicorn/recommended`,
    `plugin:prettier/recommended`,
    `prettier`,
  ],
  parser: `@typescript-eslint/parser`,
  rules: {
    curly: [`error`, `all`],
    quotes: [`error`, `backtick`],
    camelcase: `off`,
    'no-shadow': `off`,
    'no-irregular-whitespace': `off`,
    'no-underscore-dangle': `off`,
    'no-unused-vars': `off`,
    'jsx-a11y/label-has-associated-control': `off`,
    'jsx-a11y/click-events-have-key-events': `off`,
    'jsx-a11y/no-static-element-interactions': `off`,
    'jsx-a11y/no-noninteractive-element-interactions': `off`,
    'no-use-before-define': `off`,
    '@typescript-eslint/no-use-before-define': `error`,
    '@typescript-eslint/explicit-module-boundary-types': `off`,
    'react/react-in-jsx-scope': `off`,
    'react/prop-types': `off`,
    'react/require-default-props': `off`,
    'react/no-unescaped-entities': `off`,
    'react/no-array-index-key': `off`,
    'react/jsx-filename-extension': [2, { extensions: [`.js`, `.jsx`, `.ts`, `.tsx`] }],
    'import/prefer-default-export': `off`,
    'import/extensions': [
      `error`,
      `ignorePackages`,
      { js: `never`, jsx: `never`, ts: `never`, tsx: `never` },
    ],
    '@typescript-eslint/indent': `off`,
    '@typescript-eslint/no-unused-vars': `error`,
    '@typescript-eslint/no-shadow': `error`,
    'unicorn/no-null': `off`,
    'unicorn/no-array-reduce': `off`,
    'unicorn/new-for-builtins': `off`,
    'unicorn/numeric-separators-style': [`error`, { number: { minimumDigits: 0, groupLength: 3 } }],
    'unicorn/filename-case': `off`,
  },
  overrides: [
    {
      files: [`*.stories.*`],
      rules: {
        'no-shadow': 0,
        'import/no-extraneous-dependencies': 0,
        'react/jsx-props-no-spreading': 0,
        '@typescript-eslint/no-use-before-define': 0,
      },
    },
  ],
  settings: {
    'import/resolver': {
      typescript: {},
    },
  },
}
